import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

function Home() {
    const [windowHeight, setWindowHeight] = useState(1080)
    const [picRight, setPicRight] = useState(windowHeight * 0.7)
    const [scrollY, setScrollY] = useState(-1)
    const [backgroundBlur, setBackgroundBlur] = useState(0)
    const [opacity, setOpacity] = useState(0)
    const [transitionTime, setTransitionTime] = useState(0)
    const [slideIn, setSlideIn] = useState(0)
    const [slideDown, setSlideDown] = useState(0)
    const [moveTime, setMoveTime] = useState(0)

    const handleScroll = () => {
        setTransitionTime(1000)

        setScrollY(window.scrollY)
    }

    const handleResize = async () => {
        setWindowHeight(window.innerHeight)

        let right = windowHeight * 0.7
        setPicRight(right)
    }

    useEffect(() => {
        window.addEventListener('resize', handleResize)
        window.addEventListener('scroll', handleScroll)

        return () => {
            window.removeEventListener('resize', handleResize)
            window.removeEventListener('scroll', handleScroll)
        }
    })

    useEffect(() => {
        {
            /* Background stuff */
        }
        let backgroundBlurVar = scrollY / 15
        let opacityVar = 120 - backgroundBlurVar * 4

        setOpacity(opacityVar)
        if (backgroundBlurVar < 50 && opacityVar < 20) {
            opacityVar = 20
            setOpacity(opacityVar)
        } else if (backgroundBlurVar > 50) {
            opacityVar = 0
            setOpacity(opacityVar)
        }
        backgroundBlurVar >= 20
            ? setBackgroundBlur(20)
            : setBackgroundBlur(backgroundBlurVar)

        {
            /* Text 'Animation' */
        }
    }, [scrollY])

    useEffect(() => {
        setWindowHeight(window.innerHeight)
        setPicRight(windowHeight * 0.7)
    }, [windowHeight])

    useEffect(() => {
        if (scrollY == -1) {
            window.scrollTo({
                top: 300,
                left: 0,
                behavior: 'smooth',
            })
        }
    })

    return (
        <div className={styles.container}>
            <Head>
                <title>Javahound - Dev, creator, fluffy</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <header className="heightFull">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                        className="background"
                        style={{
                            filter: `blur(${backgroundBlur}px)`,
                            opacity: `${opacity}%`,
                            right: `-${picRight}px`,
                            transition: `${transitionTime}ms ease-out`,
                        }}
                        src={'/avtrPicFull.png'}
                        alt={''}
                        height={`${windowHeight}`}
                    />
                </header>
                <div
                    style={{
                        margin: `${slideDown}px 0px 200px ${slideIn}px`,
                        transition: `${moveTime}ms ease-in-out`,
                    }}
                >
                    <h2>Javahound</h2>
                    <h3>
                        Full Stack Dev, creator, Furry, <br />
                        VR Enthusiast
                    </h3>
                </div>
            </main>

            <footer className={styles.footer}>
                <a href="" target="" rel="noopener noreferrer">
                    Powered by my <h3>&nbsp;caffeine Addiction</h3>
                </a>
            </footer>
        </div>
    )
}

Home.defaultProps = {
    keywords:
        'javahound, furry, vr, vrfurry, vr furry, content creation, web development, programming',
    description: 'Full Stack Dev, creator, Furry',
}

export default Home
